name: 'Main Workflow'
on: [push]
jobs:
  checks:
    name: 'Check Code Style'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.X'
    - run: echo 'This could be your code style check'
    - run: python -c "import sys; print(sys.version)"
    - run: pwd
    - run: ls -al
  sdist:
    name: "Bundle Distribution"
    runs-on: ubuntu-latest
    steps:
    - run: echo "Build the Distribution"
  deploy:
    name: "Deploy Release"
    runs-on: ubuntu-latest
    needs: [checks, sdist]
    steps:
    - run: echo "Upload the Distribution"
